### ISSUE TITLE
Issues installing on MacOS Sonoma, Python 3.11 and 3.12

### ISSUE THREAD

**Issue by neilyoung** [skymaze/pymediasoup#7]
While trying to install `pymediasoup` in the a.m. environment I'm appearing troubles, most likely with the AV submodule.

```
(ms) ~ $ pip install pymediasoup
Collecting pymediasoup
  Using cached pymediasoup-0.2.2-py3-none-any.whl (41 kB)
Collecting aiortc<2.0.0,>=1.2.0 (from pymediasoup)
  Downloading aiortc-1.5.0.tar.gz (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 4.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting h264-profile-level-id<2.0.0,>=1.0.0 (from pymediasoup)
  Using cached h264_profile_level_id-1.0.0-py2.py3-none-any.whl (5.0 kB)
Collecting pydantic<2.0.0,>=1.8.1 (from pymediasoup)
  Obtaining dependency information for pydantic<2.0.0,>=1.8.1 from https://files.pythonhosted.org/packages/39/9f/ab6d19c5d3fccc1e3e0d835ac773031388802b31d93937daf878465c2ecf/pydantic-1.10.13-py3-none-any.whl.metadata
  Downloading pydantic-1.10.13-py3-none-any.whl.metadata (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.6/149.6 kB 4.5 MB/s eta 0:00:00
Collecting pyee<9.0.0,>=8.1.0 (from pymediasoup)
  Using cached pyee-8.2.2-py2.py3-none-any.whl (12 kB)
Collecting sdp-transform<2.0.0,>=1.0.1 (from pymediasoup)
  Obtaining dependency information for sdp-transform<2.0.0,>=1.0.1 from https://files.pythonhosted.org/packages/0e/47/80a3782ebe97cddb5c91f22e736cb5270288b11b1829d6943d75b90d7d5a/sdp_transform-1.0.6-py3-none-any.whl.metadata
  Using cached sdp_transform-1.0.6-py3-none-any.whl.metadata (598 bytes)
Collecting aioice<1.0.0,>=0.9.0 (from aiortc<2.0.0,>=1.2.0->pymediasoup)
  Using cached aioice-0.9.0-py3-none-any.whl (24 kB)
Collecting av<11.0.0,>=9.0.0 (from aiortc<2.0.0,>=1.2.0->pymediasoup)
  Downloading av-10.0.0.tar.gz (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 3.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [80 lines of output]
      Compiling av/plane.pyx because it changed.
      [1/1] Cythonizing av/plane.pyx
      Compiling av/dictionary.pyx because it changed.
      [1/1] Cythonizing av/dictionary.pyx
      Compiling av/stream.pyx because it changed.
      [1/1] Cythonizing av/stream.pyx
      Compiling av/option.pyx because it changed.
      [1/1] Cythonizing av/option.pyx
      Compiling av/enum.pyx because it changed.
      [1/1] Cythonizing av/enum.pyx
      Compiling av/bytesource.pyx because it changed.
      [1/1] Cythonizing av/bytesource.pyx
      Compiling av/buffer.pyx because it changed.
      [1/1] Cythonizing av/buffer.pyx
      Compiling av/packet.pyx because it changed.
      [1/1] Cythonizing av/packet.pyx
      Compiling av/error.pyx because it changed.
      [1/1] Cythonizing av/error.pyx
      Compiling av/_core.pyx because it changed.
      [1/1] Cythonizing av/_core.pyx
      Compiling av/format.pyx because it changed.
      [1/1] Cythonizing av/format.pyx
      performance hint: av/logging.pyx:232:5: Exception check on 'log_callback' will always require the GIL to be acquired.
      Possible solutions:
          1. Declare the function as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
          2. Use an 'int' return type on the function to allow an error code to be returned.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      cdef const char *log_context_name(void *ptr) nogil:
          cdef log_context *obj = <log_context*>ptr
          return obj.name
      
      cdef lib.AVClass log_class
      log_class.item_name = log_context_name
                            ^
      ------------------------------------------------------------
      
      av/logging.pyx:216:22: Cannot assign type 'const char *(void *) except? NULL nogil' to 'const char *(*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'const char *(void *) except? NULL nogil'.
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
      
      # Start the magic!
      # We allow the user to fully disable the logging system as it will not play
      # nicely with subinterpreters due to FFmpeg-created threads.
      if os.environ.get('PYAV_LOGGING') != 'off':
          lib.av_log_set_callback(log_callback)
                                  ^
      ------------------------------------------------------------
      
      av/logging.pyx:351:28: Cannot assign type 'void (void *, int, const char *, va_list) except * nogil' to 'av_log_callback'. Exception values are incompatible. Suggest adding 'noexcept' to type 'void (void *, int, const char *, va_list) except * nogil'.
      Compiling av/logging.pyx because it changed.
      [1/1] Cythonizing av/logging.pyx
      Traceback (most recent call last):
        File "/Users/decades/anaconda3/envs/ms/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/decades/anaconda3/envs/ms/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/decades/anaconda3/envs/ms/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/7l/rc18f0m564qgtmjlzn6b_n5m0000gn/T/pip-build-env-hqi7pcce/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/7l/rc18f0m564qgtmjlzn6b_n5m0000gn/T/pip-build-env-hqi7pcce/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/7l/rc18f0m564qgtmjlzn6b_n5m0000gn/T/pip-build-env-hqi7pcce/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/7l/rc18f0m564qgtmjlzn6b_n5m0000gn/T/pip-build-env-hqi7pcce/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 157, in <module>
        File "/private/var/folders/7l/rc18f0m564qgtmjlzn6b_n5m0000gn/T/pip-build-env-hqi7pcce/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/7l/rc18f0m564qgtmjlzn6b_n5m0000gn/T/pip-build-env-hqi7pcce/overlay/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: av/logging.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: There was an error checking the latest version of pip.
(ms) ~ $ 

```

Anybody heard about? Any idea, what to do with this?

**Comment by neilyoung** [comment]
PS: It works in a 3.9 VM. It also does not install in a 3.10 VM, but there with another error.

I'm fine with 3.9

**Comment by neilyoung** [comment]
I'm seeing right now there is only support up to 3.9.

**Comment by skymaze** [comment]
v0.2.5 now supports python3.11
